### PR TITLE
Operations v4

### PR DESCRIPTION
**Pull request by CDJellen**
## Description

Adjustments to the `Operation Results` page in the readthedocs. Core changes are to the stated best practices for exploring an operation after completion, with mention of Debrief, and correction/updating of the Operation Report structure and example.

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

All documentation changes were made to the markdown and previewed in Visual Studio Code to ensure proper links.  The new hyperlinks are worth reviewing, but I've matched the format for existing (and working) links as they appear elsewhere in `fieldmanual`.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by CDJellen** [comment]
I'll request a merge after one approval, extra reviewers added only to expedite v4 documentation fixes.

**Review by djlawren — APPROVED** [review]
Looks good to me.

**Review by elegantmoose — APPROVED** [review]

**Comment by CDJellen** [comment]
@wbooth This documentation change should be ready to merge,

**Comment by uruwhy** [comment]
Am I missing something? Did the operation event logs documentation get moved elsewhere, or are we just removing it entirely?

**Review by uruwhy — CHANGES_REQUESTED** [review]
Am I missing something? Are we moving the operation event logs documentation elsewhere or just removing it entirely?

**Comment by CDJellen** [comment]
@uruwhy The event log generation section was not moved, and still appears after the sample Operation Report.  We could consider moving it above the sample, but in the current state it has not moved and was not modified (It appears at line 629 of the current PR).

**Comment by uruwhy** [comment]
> @uruwhy The event log generation section was not moved, and still appears after the sample Operation Report. We could consider moving it above the sample, but in the current state it has not moved and was not modified (It appears at line 629 of the current PR).

I'm referring to the event log documentation and examples that used to be in the `## Operation Event Logs` section. It looks like that entire piece got deleted in this PR

**Comment by CDJellen** [comment]
@uruwhy Thanks for catching this!  The event log samples and overview, as well as the automatic event log generation now appear properly in the document.  The change to headers should also keep automatic event log generation properly nested under `Operation Event Logs`.

The file structure for operation reports was changed between 3.1 and present, but the event log structure appears the same from the samples I've taken.  I'll do one more re-review and cross-check on linking pages.

**Comment by uruwhy** [comment]
> @uruwhy Thanks for catching this! The event log samples and overview, as well as the automatic event log generation now appear properly in the document. The change to headers should also keep automatic event log generation properly nested under `Operation Event Logs`.
> 
> The file structure for operation reports was changed between 3.1 and present, but the event log structure appears the same from the samples I've taken. I'll do one more re-review and cross-check on linking pages.

Great! Let me know when you're ready for us to re-review on our end

**Review by uruwhy — APPROVED** [review]
LGTM!

**Pull request merged**
